version: 2
updates:
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"
      time: "10:00"
      timezone: "Europe/Moscow"
    commit-message:
      prefix: "dependabot"
    labels:
      - "update dependency"
    pull-request-branch-name:
      separator: "/"
    # ignore eslint version due to my webstorm 2020.3 does not support eslint > 7.32.0
    ignore:
      - dependency-name: "eslint"