version: 2
updates:
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"
      time: "10:00"
      timezone: "Europe/Moscow"
    commit-message:
      prefix: "dependabot"
    labels:
      - "update dependency"
    pull-request-branch-name:
      separator: "/"
    ignore:
      - dependency-name: "sass-loader"    # https://stackoverflow.com/questions/66082397/typeerror-this-getoptions-is-not-a-function
      - dependency-name: "node-fetch"
      - dependency-name: "@nuxt/content"  # can not upgrade to the highest version